export enum PaymentChannel {
    Card = "card",
    OrangeMoneySenegal = "orange-money-senegal",
    WaveSenegal = "wave-senegal",
    FreeMoneySenegal = "free-money-senegal",
    ExpressoSn = "expresso-sn",
    WizallSenegal = "wizall-senegal",
    MtnBenin = "mtn-benin",
    MoovBenin = "moov-benin",
    OrangeMoneyCi = "orange-money-ci",
    WaveCi = "wave-ci",
    MtnCi = "mtn-ci",
    MoovCi = "moov-ci",
    TMoneyTogo = "t-money-togo",
    MoovTogo = "moov-togo",
    OrangeMoneyMali = "orange-money-mali",
    MoovMl = "moov-ml",
    OrangeMoneyBurkina = "orange-money-burkina",
    MoovBurkinaFaso = "moov-burkina-faso"
}